### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by VansonLeung** [jrans/react-native-smart-scroll-view#11]
Lack of android support renders this plugin useless IMHO.
Do you mind if I would submit PR for android support sooner or later?

**Comment by nikhilaravi** [comment]
@VansonLeung yes that would be great, please do submit a PR. Thanks!

**Comment by VansonLeung** [comment]
[FAIL] After trying I figured the current RN Android scroll view has its own native way to scroll itself upon focus / blur. The worst of all, I can't control it by DeviceEventEmitter because Android build of React Native does not have "keyboardWillShow" or "keyboardWillHide" callbacks. So Fail.

**Comment by geirman** [comment]
I'm confused. Is this closed because it could not be done? If it couldn't be done (yet!), shouldn't it remain open?

Looking through the code, it [appears there's some platform specific logic when setting the event handlers](https://github.com/jrans/react-native-smart-scroll-view/blob/master/SmartScrollView.js#L53-L54). 

So, is Android supported or not? If so, then the readme needs to be updated. It says "A pure JS React Native Component for IOS."
